services:
  api:
    build: .
    restart: "no"
    deploy:
      replicas: 1
    networks:
      - app-network
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge